version: '3.8'

services:
  app:
    build: .
    container_name: agente-vendas
    ports:
      - "8081:8081"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    volumes:
      # Mount only essential files
      - ./credentials.json:/app/credentials.json:ro
      - ./token.json:/app/token.json:ro
      - ./apps_script_url.txt:/app/apps_script_url.txt:ro
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/data"]
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 20s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
