version: '3.8'

services:
  app:
    build: .
    container_name: agente-vendas-dev
    ports:
      - "8081:8081"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FLASK_APP=app.py
    volumes:
      # Mount source code for hot reload
      - .:/app
      - /app/__pycache__
      - /app/.git
    restart: unless-stopped
    command: python app.py
